### ISSUE TITLE
need: bare-bones profile input form for testing 

### ISSUE THREAD

**Issue by the-vampiire** [the-vampiire/chingu-chimp#2]
a bare-bones profile input form that can be used for testing the backend

**Comment by the-vampiire** [comment]
add back the certifications field: 

certifications: [{
        name: String,
        url: {type: String, default: false},
        date: Number
    }]

and update the form schema to include a dropdown selections array of certifications
this will only be FCC certifications so we can make a dropdown of it
url is the certificate url

**Comment by the-vampiire** [comment]
@Jcroxford go ahead and close this one. You finished it!

**Comment by Jcroxford** [comment]
bare bones form has been added to public folder. Closing issue.
