### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by thatrobotdev** [the-vampiire/chingu-chimp#6]
I think it would be cool if you created a readme, so I knew what your project was about! It would really help with other people as well.

**Comment by Jcroxford** [comment]
Thanks for the suggestion! We already have a basic readme skeleton in place. It will be merged in master shortly. A more mature read me will follow as soon as the project enters beta

**Comment by Jcroxford** [comment]
Readme has been merged and can now be seen on [master.](https://github.com/the-vampiire/chingu-chimp)
